# makefile for Virtual Memeory Unit
#
# make mmu128 - for physical address space with 128 page frames
# make mmu256 - for physical address space with 256 page frames

CC=gcc
CFLAGS=-Wall

clean:
	rm -rf *.o
	rm -rf mmu128
	rm -rf mmu256
	
mmu: 
	$(CC) $(CFLAGS) -o mmu ... 